openapi: 3.0.0
info:
  title: Blackjack REST API
  version: 1.0.0
paths:
  /blackjack:
    post:
      summary: Create a new game
      description: Create a new game of blackjack
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponse'
        '400':
          description: Bad request
  /blackjack/{game_id}:
    delete:
      summary: Delete a blackjack game
      description: Delete a blackjack game
      parameters:
        - in: path
          name: game_id
          required: true
          schema:
            type: string
            format: uuid
          description: The ID of the blackjack game to delete
      responses:
        '204':
          description: The blackjack game was successfully deleted
        '403':
          description: The access token did not enable you to delete this blackjack game
        '404':
          description: The blackjack game ID was not found
      security:
        - bearerAuth: []
  /blackjack/{game_id}/play:
    post:
      summary: Play a blackjack game
      description: Play a blackjack game
      parameters:
        - in: path
          name: game_id
          required: true
          schema:
            type: string
            format: uuid
          description: The ID of the blackjack game to play
        - in: query
          name: action
          required: true
          schema:
            type: string
            enum:
              - hit
              - stand
              - double
              - split
          description: The action to take in the blackjack game
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameState'
        '400':
          description: Bad request
        '403':
          description: The access token did not enable you to play this blackjack game
        '404':
          description: The blackjack game ID was not found
      security:
        - bearerAuth: []
      

components:
  schemas:
    GameResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        access_token:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
    GameState:
      type: object
      properties:
        player_hand:
          type: array
          items:
            $ref:
             '#/components/schemas/Card'
        dealer_hand:
          type: array
          items:
            $ref:
             '#/components/schemas/Card'
        player_score:
          type: integer
          example: 21
        dealer_score:
          type: integer
          example: 17
        player_options:
          type: array
          items:
            type: string
            enum:
              - hit
              - stand
              - double
              - split
          example: hit
        winner:
          type: string
          enum:
            - player
            - dealer
            - tie
          example: player
    Card:
      type: object
      properties:
        rank:
          type: string
          example: A
        suit:
          type: string
          example: d
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
