name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            # Add multiple commands to run if needed

            cargo build --verbose || exit 1
            cargo test --verbose || exit 1
            cargo fmt --check || exit 1
            cargo clippy || exit 1
